Community docs
clairefro/mintbean-cli pull request #35
Opened 2020-08-31 21:05 UTC by KmBarnett

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [x] Documentation Update

## Description

This PR Adds contributing guide

## Added to documentation?

- [ ] readme
- [ ] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](https://media.giphy.com/media/igbomc6YEwCS566BJO/giphy.gif)

2020-09-03 23:28 UTC, monarchwadia approved these changes, later dismissed

2020-09-03 23:28 UTC, monarchwadia commented on .github/ISSUE_TEMPLATE/bug_report.md
> +labels: 'bug'~~~~~~~~
What is `~~~~~` ?

2020-09-03 23:28 UTC, monarchwadia commented
@KmBarnett one comment that may or may not need a fix.

2020-09-03 23:34 UTC, KmBarnett commented on .github/ISSUE_TEMPLATE/bug_report.md
> +labels: 'bug'~~~~~~~~
fixed

2020-09-08 16:34 UTC, clairefro requested changes
this PR was a lottttt more than updating the community docs lol

You mentioned you were experiencing trouble with `import/require` statements, and I see a mish-mash of both types in the code. 

If we decide to go the `import` route, maybe we try one of below:
```
TLDR;

Node >= v13

It's very simple in Node 13 and above. You need to either:

Save the file with .mjs extension, or
Add { "type": "module" } in the nearest package.json.
```

https://stackoverflow.com/questions/45854169/how-can-i-use-an-es6-import-in-node

2020-09-08 16:34 UTC, clairefro commented on README.md
> +cd
add project name to clarify cd
```
mint new <my-project>
cd <my-project>
```

2020-09-08 16:34 UTC, clairefro commented on docs/how_to_contribute.md
> +Do you want a new template? Check out the adding new templates guide also in the Docs folder.
include a link to the guide

2020-09-08 17:05 UTC, KmBarnett commented on README.md
> +cd
done

2020-09-08 17:05 UTC, KmBarnett commented on docs/how_to_contribute.md
> +Do you want a new template? Check out the adding new templates guide also in the Docs folder.
done

2020-09-08 17:17 UTC, clairefro requested changes
Thanks for updating docs

We cannot approve this branch until it passes Buddy tests. Logs show that `jest` is not installed - that is why test is failing. Can you add jest and get tests to pass locally before pushing again?
 
![image](https://user-images.githubusercontent.com/9841162/92507812-6b072f00-f1bc-11ea-98d3-7f37b5cd8703.png)

2020-09-08 17:30 UTC, clairefro approved these changes

2020-09-08 17:31 UTC, clairefro commented
Merging for now but it is urgent that we include tests in the Buddy pipeline soon

2020-09-08 17:32 UTC, merged

2020-09-08 17:32 UTC, clairefro commented
Merging but it is urgent we write tests and include in Buddy pipeline soon