Bug/securetoken
clairefro/mintbean-cli pull request #71
Opened 2020-11-28 06:41 UTC by nachiket87

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Fixed issue [#51 ](https://github.com/Mintbean/mintbean-cli/issues/51 )

## Added to documentation?

- [ ] readme
- [X] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif url)

2020-12-16 22:45 UTC, nachiket87 commented
Are there any reviewers?

2020-12-17 01:11 UTC, clairefro commented
> Are there any reviewers?

Hi! Thanks again for this feature fix. 

We haven't forgotten this and will get to it soon. Apologies that we've been internally backlogged and it's taken us some time to review.

2021-01-04 16:02 UTC, KmBarnett requested changes
The code is mostly good it just needs to be restructured. There are a few that need to be undone or explained.

2021-01-04 16:02 UTC, KmBarnett commented on commands/config.js
> +      `token:            ${getConfig("token") ? `<hidden>` : "undefined"}`
Is there a reason quotes had to be changed? For consistency purposes, if they didn't need to be changed, revert this back.

2021-01-04 16:02 UTC, KmBarnett commented on program.js
> +    .option("-t, --token", "set github personal access token")
`<token>` made the token a required argument for this command; Why did you remove it? Setting a Github token to undefined and getting the message `Successfully set GitHub personal access token.` is a bad flow.

2021-01-04 16:02 UTC, KmBarnett commented on commands/new.js
> +const TOKEN = {
This file is for the creation of new projects not for adding to the config. Lines 21-28 and lines 112-119 need to be extracted to a new file

2021-01-04 18:51 UTC, nachiket87 commented
Accidentally request review again. Please ignore.

2021-01-04 18:57 UTC, closed without merging

2021-01-04 19:00 UTC, nachiket87 commented
I currently have an unsolvable node / yarn issue in running the cli on dev. I don't think I can fix this. Thanks for the time.